### ISSUE TITLE
任何程序都报错无法

### ISSUE THREAD

**Issue by HasonWang** [fallingmeteorite/Wraith_Toolbox#1]
UI Console:
![image](https://github.com/fallingmeteorite/Wraith_Toolbox/assets/113149863/b83b8812-dc14-4db9-a9c2-648f283e5091)
CMD Console:
📢 Tips: QFluentWidgets Pro is now released. Click https://qfluentwidgets.com/pages/pro to learn more about it.

QFSFileEngine::open: No file name specified
QIODevice::read (QFile, ""): device not open
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
F:\ImageProccesPro\Image_process_pro\Environment\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
F:\ImageProccesPro\Image_process_pro\Environment\lib\site-packages\gradio\helpers.py:818: UserWarning: Using the update method is deprecated. Simply return a new object instead, e.g. `return gr.Textbox(...)` instead of `return gr.update(...)
  warnings.warn(
┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ F:\ImageProccesPro\Image_process_pro\Image_process_pro_Data\02\Run.py:36 in │
│ <module>                                                                    │
│                                                                             │
│   33 parameter07 = args.parameter07                                         │
│   34 parameter08 = args.parameter08                                         │
│   35                                                                        │
│ > 36 Thread_calls(parameter01, parameter02, parameter03, parameter04, param │
│   37                                                                        │
│                                                                             │
│ in Multithreaded.Thread_calls:50                                            │
└─────────────────────────────────────────────────────────────────────────────┘
TypeError: object of type 'int' has no len()

**Comment by fallingmeteorite** [comment]
你可能是使用3.0.0的版本直接用更新器更新至4.0.0导致的,你应该删除现有文件夹，从以下链接下载4.0.0并使用更新器更新
123网盘https://www.123pan.com/s/5Hstjv-nZROA.html（不限速）

百度链接https://pan.baidu.com/s/1B1kXtfMMgaokWMFt3QD6gQ?pwd=kj4q （会限速）
然后：
下载该链接文件解压并覆盖用于修复启动错误：https://github.com/fallingmeteorite/Image_process_pro/releases/download/update/Image_process_pro.zip


因为在我这，功能正常运行
![Uploading 68b5c6bfa9c1894e53696b062042b17b.png…]()

**Comment by fallingmeteorite** [comment]
你可能是使用3.0.0的版本直接用更新器更新至4.0.0导致的,你应该删除现有文件夹，从以下链接下载4.0.0并使用更新器更新
123网盘[https://www.123pan.com/s/5Hstjv-nZROA.html（不限速）](https://www.123pan.com/s/5Hstjv-nZROA.html%EF%BC%88%E4%B8%8D%E9%99%90%E9%80%9F%EF%BC%89)

百度链接https://pan.baidu.com/s/1B1kXtfMMgaokWMFt3QD6gQ?pwd=kj4q （会限速）
然后：
下载该链接文件解压并覆盖用于修复启动错误：https://github.com/fallingmeteorite/Image_process_pro/releases/download/update/Image_process_pro.zip

因为在我这，功能正常运行
![1](https://github.com/fallingmeteorite/Wraith_Toolbox/assets/86793086/5e611f2e-9afd-4bd2-a19e-05d805f1ad2b)
